environment:
  base_version: '3.0.3'
  version_suffix: ''
version: $(base_version).{build}
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(base_version)$(version_suffix)'
  package_version: '$(base_version)$(version_suffix)'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '$(base_version)$(version_suffix)'
before_build:
- ps: dotnet restore
after_build:
- ps: dotnet pack -c release
build:
  verbosity: minimal
  publish_nuget: true
test_script:
- ps: dotnet test .\YahooQuotesApi.Tests\YahooQuotesApi.Tests.csproj
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true
artifacts:
- path: '**\*.nupkg'
